display = "cunningweb"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://dnzin.com/cunningweb"
title = "cunningweb"
years = [ 2007 ]
