display = "Cyberstampers"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.cyberstampers.com/"
title = "Cyberstampers"
years = [ 2008 ]
