display = "Eff Seven"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://effseven.co.uk/"
title = "Eff Seven"
years = [ 2008 ]
