display = "hidden web"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.pageoff.net/"
title = "hidden web"
years = [ 2008 ]
