display = "Israel Viana"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.israelviana.es/"
title = "Israel Viana"
years = [ 2009 ]
