display = "Nikita Karamov"
email = "me@kytta.dev"

# Websites

[[websites]]
url = "https://www.kytta.dev"
years = [ 2026 ]

# Accounts

[[accounts]]
type = "Fediverse"
url = "https://polymaths.social/@kytta"
