display = "Logan Leger"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.loganleger.com/"
title = "Logan Leger"
years = [ 2006 ]
