display = "Point studios"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://point-studios.com/"
title = "Point studios"
years = [ 2007 ]
