display = "prower"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.prower.cn/"
title = "prower"
years = [
	2008,
	2009 
]
