display = "redbeanking"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://redbeanking.spaces.live.com/"
title = "redbeanking"
years = [ 2008 ]
