display = "seopost"

# Websites
# ------------------------------------------------------------------------------

[[websites]]
url   = "https://web.archive.org/web/http://www.seopost.ru/"
title = "seopost"
years = [ 2008 ]
